### PR TITLE
Optionally report the count of log entries to a MetricsAgent

### PR DESCRIPTION
**Pull request by acoulton**
Add the ability for the StackdriverApplicationLogger to increment
a counter for each log entry written.

### CODE REVIEW

**Comment by acoulton** [comment]
@craig410 I'm wondering whether rather than exposing this as a setter it'd be better as a `::withMetricsAgent(agent, destination, metadatas...)` named constructor. The logger is obv very widely exposed and the metrics bit shouldn't really be modifiable at runtime. WDYT?

**Comment by craig410** [comment]
I was thinking it should be an optional constructor dependency and then initialise a NullMetricsAgent in the constructor if it's not present. Lets you hard type-hint the property and always call it which will result in a no-op unless you've attached a 'real' one. And if you didn't want to pollute the current constructor then a named constructor would probably be better?

**Comment by acoulton** [comment]
@craig410 better? Annoyingly because the existing constructor is variadic there's no scope to add more args.

**Review by craig410 — APPROVED** [review]
Think this is better. LGTM

**Pull request merged**
